from typing import TypedDict, List, Dict, Any, Optional, Sequence
from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    # ── Core conversation ────────────────────────────────────────
    messages: List[BaseMessage]
    active_model: str
    user_id: str
    chat_id: str
    retrieved_documents: List[Dict[str, Any]]
    metrics: Dict[str, Any]
    response_text: str
    tool_calls: Optional[List[Dict[str, Any]]]
    steps: List[str]

    # ── Intent Classifier (NEW — P0 fix) ─────────────────────────
    # The intent detected by classify_intent_node before any routing.
    # One of: MEMORY_WRITE | NORMAL_CHAT | WEB_SEARCH | CODE_EXECUTION |
    #         MCP_TOOL | DOCUMENT_QA | VISION | COMPLEX
    intent: str

    # Whitelist of tool names that may be injected for this specific turn.
    # An empty list means NO tools are offered to the LLM (pure generation).
    # Populated by classify_intent_node using INTENT_TOOL_WHITELIST.
    allowed_tools: List[str]

    # True when the query is about the user's own private uploaded documents.
    # When True, grade_documents_node will NOT trigger the Tavily web fallback
    # (prevents private-intent leakage to external APIs).
    is_private_doc_query: bool

    # True when a private-doc query found no relevant chunks — instructs the
    # LLM to respond with "not found in documents" rather than hallucinating.
    no_doc_answer: bool

    # ── Memory Write (NEW — P0 fix) ──────────────────────────────
    # Extracted memory content and category from classify_intent_node.
    # Used exclusively by memory_write_node to persist the fact.
    memory_write_content: Optional[str]
    memory_write_category: Optional[str]

    # ── Uploaded file paths (NEW — P0 fix) ───────────────────────
    # Server-side absolute paths to the user's currently uploaded files.
    # Injected into the system prompt so the LLM can reference them in code.
    uploaded_file_paths: Optional[List[str]]

    # ── Planner ──────────────────────────────────────────────────
    # List of task steps generated by the planner node for complex queries.
    plan: Optional[List[str]]
    # Index into `plan` currently being executed (0-based).
    current_plan_step: int

    # ── Self-RAG: retrieval necessity check ──────────────────────
    # True  → retrieve context from vector store before generating.
    # False → skip retrieval (simple/conversational queries).
    needs_retrieval: bool

    # ── CRAG: document relevance grading ─────────────────────────
    # After retrieval, the grader classifies the corpus:
    #   "relevant"        → chunks are useful; proceed.
    #   "irrelevant"      → chunks don't match; fallback to web search
    #                        (only if is_private_doc_query is False).
    #   "mixed"           → some chunks useful; keep relevant subset.
    #   "no_docs"         → user has no uploaded documents.
    #   "no_private_docs" → private-doc query but no relevant chunks found;
    #                        LLM instructed to say "I don't know".
    document_relevance: str

    # ── Reflection ───────────────────────────────────────────────
    # Natural-language critique produced by the reflection node.
    reflection_feedback: Optional[str]
    # True  → response passed quality check; export to user.
    # False → needs another generation pass with the critique injected.
    reflection_passed: bool
    # Counts how many generate_response cycles have run; prevents
    # infinite reflection loops (capped at MAX_ITERATIONS in graph.py).
    iteration_count: int

    # ── Citations ────────────────────────────────────────────────
    # Numbered list of source documents returned to the frontend so
    # the UI can render inline citation badges [1], [2], …
    source_documents: List[Dict[str, Any]]

    # ── Vision ───────────────────────────────────────────────────
    # List of inline image payloads (base64-encoded) attached by the user.
    # Each entry: {"base64": str, "mimeType": str}
    images: Optional[List[Dict[str, str]]]

    # ── Self-RAG evaluation & retry ──────────────────────────────
    retrieval_retry_count: int
    max_retrieval_retries: int
    retrieval_confidence: float

    # ── Clarification ────────────────────────────────────────────
    is_ambiguous: bool
    clarification_question: Optional[str]
    resolved_query: Optional[str]
    original_query: Optional[str]

    # ── Phase 3: Tool Planner & Parallel Execution ────────────────────
    # JSON-serializable DAG of tool tasks generated by tool_planner_node.
    # Each entry: {id, tool, args, depends_on, timeout, retries}
    tool_dag: Optional[List[Dict[str, Any]]]

    # Results from the parallel tool execution scheduler.
    # Each entry: {id, tool, status, output, latency_ms, attempts}
    tool_execution_results: Optional[List[Dict[str, Any]]]

    # ── Phase 3: Evidence Checker / Hallucination Detection ──────────
    # Confidence (0.0–1.0) of the final response being grounded in evidence
    answer_confidence: float
    # True if the evidence checker found unsupported claims in the answer
    has_hallucination_risk: bool
    # Number of unsupported claims corrected by the evidence checker
    unsupported_claims_count: int
    # Final verified response text (post-evidence-checking)
    verified_response: Optional[str]

    # ── Phase 3: Streaming UX stage ───────────────────────────────────
    # Human-readable stage emitted to the frontend during processing.
    # e.g. "Planning...", "Searching...", "Verifying..."
    ux_stage: Optional[str]

    # ── Phase 3: Per-chunk citations ──────────────────────────────────
    # Enriched citation list with page numbers and chunk IDs
    # Each entry: {index, filename, page_number, chunk_id, confidence, content_snippet}
    citations: Optional[List[Dict[str, Any]]]

    # ── Phase 3: Telemetry ────────────────────────────────────────────
    telemetry: Optional[Dict[str, Any]]

    # ── Multilingual ──────────────────────────────────────────────────────────
    # Language detected from the user's current message (e.g., "Hindi", "Roman Odia")
    detected_language: Optional[str]
    # Explicit language mode set by the user (e.g., "Roman Odia", "Hindi")
    # Persists for the entire conversation until the user changes it.
    language_mode: Optional[str]

    # ── Source Attribution ────────────────────────────────────────────────────
    # Tracks how the final answer was generated:
    #   "normal_rag"      — CRAG approved chunks, injected into prompt
    #   "model_knowledge" — Self-RAG skipped retrieval OR CRAG rejected all chunks
    #   "crag_rejected"   — private doc query with no relevant chunks found
    #   "web_fallback"    — CRAG triggered web search due to outdated docs
    generation_mode: Optional[str]
